//alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//audioNodeManager
export const CHANGE_ANM_NODESTRUCTURE = 'CHANGE_NODE_STRUCTURE';
export const CHANGE_ANM_ADJACENCYLIST = 'CHANGE_ANM_ADJACENCYLIST';

//activeState
export const CHANGE_ACTIVE_STATE = 'CHANGE_ACTIVE_STATE';
export const REMOVE_ACTIVE_STATE = 'REMOVE_ACTIVE_STATE_OR_SHOW_KEYBOARD';

//Values
export const SET_HAS_COLD_STARTED_TRUE = 'HAS_COLD_STARTED_TRUE';
export const SET_SHOW_KEYBOARD_TRUE = 'SHOW_KEYBOARD_TRUE';
export const SET_HAS_VALUES_CHANGED_TRUE = 'HAS_VALUES_CHANGED_TRUE';
export const SET_HAS_COMPILED_TRUE = 'HAS_COMPILED_TRUE';

export const SET_HAS_COLD_STARTED_FALSE = 'HAS_COLD_STARTED_FALSE';
export const SET_SHOW_KEYBOARD_FALSE = 'SHOW_KEYBOARD_FALSE';
export const SET_HAS_VALUES_CHANGED_FALSE = 'HAS_VALUES_CHANGED_FALSE';
export const SET_HAS_COMPILED_FALSE = 'HAS_COMPILED_FALSE';
